In [77]:
import pandas as pd
import numpy as np

In [78]:
df = pd.read_csv('ev_per_county_ny_raw.csv')
df

,REDC,County,Light-Duty Vehicles,BEVs on the Road,PHEVs on the Road,EVs on the Road,Level 2 Ports,DCFC Ports,LDVs per 1k People,BEVs per 1k People,PHEVs per 1k People,BEVS per DCFC Ports,EVs per Level 2 Port,LD EV Market Share
0,New York City,New York County,136854.0,4747.0,2190.0,6937.0,1047.0,27.0,"84,40","2,93","1,35",175.814815,"6,63","2,59%"
1,Mid-Hudson,Westchester County,389909.0,10098.0,4361.0,14459.0,368.0,109.0,"402,91","10,43","4,51",92.642202,"39,29","1,85%"
2,Southern Tier,Tompkins County,36530.0,733.0,950.0,1683.0,73.0,11.0,"354,59","7,12","9,22",66.636364,"23,05","1,67%"
3,Long Island,Nassau County,594841.0,13228.0,5337.0,18565.0,158.0,104.0,"434,31","9,66","3,90",127.192308,"117,50","1,65%"
4,Out of State,Out of State,80286.0,3640.0,757.0,4397.0,NaN,NaN,NaN,"0,00","0,00",NaN,NaN,"1,64%"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,North Country,Lewis County,15936.0,18.0,34.0,52.0,6.0,NaN,"631,10","0,71","1,35",NaN,"8,67","0,14%"
61,Western New York,Allegany County,20880.0,37.0,72.0,109.0,7.0,1.0,"454,62","0,81","1,57",37.000000,"15,57","0,13%"
62,Finger Lakes,Wyoming County,21215.0,40.0,60.0,100.0,8.0,NaN,"525,29","0,99","1,49",NaN,"12,50","0,08%"
63,NaN,NaN,NaN,NaN,NaN,NaN,6.0,0.0,NaN,"0,00","0,00",NaN,NaN,NaN
64,Unknown,Unknown,208.0,1.0,1.0,2.0,NaN,NaN,NaN,"0,00","0,00",NaN,NaN,NaN

In [79]:
df[df['REDC'] == 'New York City'] #Vemos la informaciÃ³n disponible para la regiÃ³n de interÃ©s

,REDC,County,Light-Duty Vehicles,BEVs on the Road,PHEVs on the Road,EVs on the Road,Level 2 Ports,DCFC Ports,LDVs per 1k People,BEVs per 1k People,PHEVs per 1k People,BEVS per DCFC Ports,EVs per Level 2 Port,LD EV Market Share
0,New York City,New York County,136854.0,4747.0,2190.0,6937.0,1047.0,27.0,"84,40","2,93","1,35",175.814815,"6,63","2,59%"
5,New York City,Queens County,474344.0,6903.0,4858.0,11761.0,292.0,70.0,"207,38","3,02","2,12",98.614286,"40,28","1,34%"
6,New York City,Kings County,311455.0,4903.0,2244.0,7147.0,407.0,54.0,"120,25","1,89","0,87",90.796296,"17,56","1,31%"
9,New York City,Richmond County,169198.0,2039.0,965.0,3004.0,77.0,16.0,"356,29","4,29","2,03",127.437500,"39,01","1,01%"
19,New York City,Bronx County,158998.0,1134.0,574.0,1708.0,73.0,12.0,"110,51","0,79","0,40",94.500000,"23,40","0,57%"

In [80]:
#Cambiamos los nombres de county a sus equivalentes en borough, como estÃ¡n en los datasets de taxis
df['County'] = df['County'].replace(['New York County', 'Queens County', 'Kings County', 'Richmond County', 'Bronx County'], ['Manhattan', 'Queens', 'Brooklyn', 'Staten Island', 'Bronx'])
df[df['REDC'] == 'New York City'] #Vemos la informaciÃ³n disponible para la regiÃ³n de interÃ©s

,REDC,County,Light-Duty Vehicles,BEVs on the Road,PHEVs on the Road,EVs on the Road,Level 2 Ports,DCFC Ports,LDVs per 1k People,BEVs per 1k People,PHEVs per 1k People,BEVS per DCFC Ports,EVs per Level 2 Port,LD EV Market Share
0,New York City,Manhattan,136854.0,4747.0,2190.0,6937.0,1047.0,27.0,"84,40","2,93","1,35",175.814815,"6,63","2,59%"
5,New York City,Queens,474344.0,6903.0,4858.0,11761.0,292.0,70.0,"207,38","3,02","2,12",98.614286,"40,28","1,34%"
6,New York City,Brooklyn,311455.0,4903.0,2244.0,7147.0,407.0,54.0,"120,25","1,89","0,87",90.796296,"17,56","1,31%"
9,New York City,Staten Island,169198.0,2039.0,965.0,3004.0,77.0,16.0,"356,29","4,29","2,03",127.437500,"39,01","1,01%"
19,New York City,Bronx,158998.0,1134.0,574.0,1708.0,73.0,12.0,"110,51","0,79","0,40",94.500000,"23,40","0,57%"

In [81]:
df.describe()

,Light-Duty Vehicles,BEVs on the Road,PHEVs on the Road,EVs on the Road,Level 2 Ports,DCFC Ports,BEVS per DCFC Ports
count,64.000000,64.000000,64.000000,64.000000,63.000000,53.000000,50.000000
mean,100320.781250,1289.421875,885.921875,2175.343750,128.031746,22.981132,58.572417
std,141244.682516,2620.005179,1552.222751,4085.716141,197.023166,33.000286,87.762473
min,208.000000,1.000000,1.000000,2.000000,5.000000,0.000000,3.583333
25%,24794.750000,74.750000,122.750000,194.000000,17.500000,8.000000,14.930000
50%,40006.500000,173.000000,255.000000,441.500000,46.000000,14.000000,36.546429
75%,107400.750000,1205.750000,951.250000,2331.250000,148.500000,23.000000,68.858333
max,709023.000000,13228.000000,9087.000000,19531.000000,1047.000000,196.000000,579.333333

In [82]:
df['Light-Duty Vehicles'].sum() #Comprobamos que el total coincide con el Dashboard oficial de PowerBI (fuente de datos)

6420530.0

In [83]:
df.info() #Vemos que hay algunos valores nulos

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65 entries, 0 to 64
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   REDC                  64 non-null     object
 1   County                64 non-null     object
 2   Light-Duty Vehicles   64 non-null     float64
 3   BEVs on the Road      64 non-null     float64
 4   PHEVs on the Road     64 non-null     float64
 5   EVs on the Road       64 non-null     float64
 6   Level 2 Ports         63 non-null     float64
 7   DCFC Ports            53 non-null     float64
 8   LDVs per 1k People    62 non-null     object
 9   BEVs per 1k People    65 non-null     object
 10  PHEVs per 1k People   65 non-null     object
 11  BEVS per DCFC Ports   50 non-null     float64
 12  EVs per Level 2 Port  62 non-null     object
 13  LD EV Market Share    63 non-null     object
dtypes: float64(7), object(7)
memory usage: 7.2+ KB

In [84]:
#Sabemos que en la fuente original (Dashboard PowerBI) los valores nulos son considerados como 0 y realizamos este cambio
df.replace(np.nan, 0, inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65 entries, 0 to 64
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   REDC                  65 non-null     object
 1   County                65 non-null     object
 2   Light-Duty Vehicles   65 non-null     float64
 3   BEVs on the Road      65 non-null     float64
 4   PHEVs on the Road     65 non-null     float64
 5   EVs on the Road       65 non-null     float64
 6   Level 2 Ports         65 non-null     float64
 7   DCFC Ports            65 non-null     float64
 8   LDVs per 1k People    65 non-null     object
 9   BEVs per 1k People    65 non-null     object
 10  PHEVs per 1k People   65 non-null     object
 11  BEVS per DCFC Ports   65 non-null     float64
 12  EVs per Level 2 Port  65 non-null     object
 13  LD EV Market Share    65 non-null     object
dtypes: float64(7), object(7)
memory usage: 7.2+ KB

In [85]:
print(df['LD EV Market Share'].unique()) #Empezamos a visualizar y corregir las filas numericas que tienen object dtype.

['2,59%' '1,85%' '1,67%' '1,65%' '1,64%' '1,34%' '1,31%' '1,19%' '1,15%'
 '1,01%' '0,84%' '0,82%' '0,71%' '0,68%' '0,66%' '0,60%' '0,57%' '0,55%'
 '0,54%' '0,52%' '0,48%' '0,47%' '0,45%' '0,44%' '0,42%' '0,40%' '0,37%'
 '0,36%' '0,35%' '0,34%' '0,33%' '0,32%' '0,31%' '0,27%' '0,26%' '0,25%'
 '0,22%' '0,21%' '0,20%' '0,19%' '0,18%' '0,15%' '0,14%' '0,13%' '0,08%' 0]

In [86]:
df['LD EV Market Share'] = df['LD EV Market Share'].str.replace('%', '')
df['LD EV Market Share'] = df['LD EV Market Share'].str.replace(',', '.')
df['LD EV Market Share'] = df['LD EV Market Share'].astype(float)
#Cambio de nombre para recordar que el valor estÃ¡ expresado en %
df.rename(columns={'LD EV Market Share': 'LD EV Market Share (%)'}, inplace=True)

In [87]:
print(df['LDVs per 1k People'].unique())
print(df['BEVs per 1k People'].unique())
print(df['PHEVs per 1k People'].unique())
print(df['EVs per Level 2 Port'].unique())

['84,40' '402,91' '354,59' '434,31' 0 '207,38' '120,25' '479,83' '394,18'
 '356,29' '435,36' '484,91' '457,36' '473,36' '534,90' '587,78' '420,38'
 '530,28' '398,30' '110,51' '577,85' '527,81' '445,70' '561,24' '545,50'
 '448,80' '529,37' '445,73' '482,93' '431,92' '437,84' '436,35' '509,86'
 '479,47' '497,55' '462,86' '500,21' '488,94' '485,12' '517,38' '471,05'
 '484,09' '537,12' '514,35' '483,91' '454,97' '449,91' '935,84' '533,78'
 '438,22' '488,23' '539,34' '473,19' '503,18' '532,41' '488,42' '484,03'
 '479,24' '498,17' '494,67' '631,10' '454,62' '525,29']
['2,93' '10,43' '7,12' '9,66' '0,00' '3,02' '1,89' '7,07' '6,33' '4,29'
 '5,07' '6,71' '3,85' '5,72' '6,50' '3,56' '4,68' '6,49' '2,12' '0,79'
 '3,68' '3,38' '2,91' '5,32' '2,67' '4,39' '4,73' '1,93' '3,08' '1,67'
 '1,83' '3,09' '2,15' '2,10' '1,50' '3,03' '2,21' '1,26' '1,20' '1,49'
 '1,94' '1,48' '1,73' '1,47' '1,33' '1,35' '2,39' '1,90' '1,85' '1,44'
 '1,97' '1,34' '1,11' '0,75' '0,71' '0,81' '0,99']
['1,35' '4,51' '9,22' '3,90' '0,00' '2,12' '0,87' '6,15' '2,94' '2,03'
 '5,78' '5,36' '4,09' '3,96' '4,18' '4,72' '4,49' '5,53' '3,65' '0,40'
 '4,20' '3,83' '6,00' '4,00' '2,77' '4,65' '2,93' '2,61' '2,58' '2,85'
 '3,18' '2,98' '3,41' '2,71' '3,76' '3,84' '2,17' '2,34' '2,97' '2,90'
 '2,44' '2,79' '2,24' '1,78' '1,86' '6,05' '2,67' '2,81' '2,27' '2,86'
 '1,70' '2,53' '2,76' '2,40' '1,61' '2,28' '2,11' '1,33' '1,57' '1,49']
['6,63' '39,29' '23,05' '117,50' 0 '40,28' '17,56' '63,41' '34,57' '39,01'
 '3,76' '9,44' '4,12' '17,93' '88,50' '2,65' '13,33' '9,83' '16,27'
 '23,40' '2,66' '8,70' '8,73' '5,82' '7,06' '23,88' '17,53' '11,45'
 '11,73' '16,76' '7,80' '13,61' '5,79' '13,00' '41,60' '5,75' '5,51'
 '26,13' '8,50' '8,90' '39,23' '10,60' '10,44' '17,96' '8,75' '15,20'
 '17,00' '2,25' '9,56' '15,07' '2,93' '14,50' '10,58' '6,32' '19,57'
 '4,78' '6,77' '13,48' '26,17' '8,44' '8,67' '15,57' '12,50']

In [88]:
df['LDVs per 1k People'] = df['LDVs per 1k People'].str.replace(',', '.')
df['LDVs per 1k People'] = df['LDVs per 1k People'].astype(float)

df['BEVs per 1k People'] = df['BEVs per 1k People'].str.replace(',', '.')
df['BEVs per 1k People'] = df['BEVs per 1k People'].astype(float)

df['PHEVs per 1k People'] = df['PHEVs per 1k People'].str.replace(',', '.')
df['PHEVs per 1k People'] = df['PHEVs per 1k People'].astype(float)

df['EVs per Level 2 Port'] = df['EVs per Level 2 Port'].str.replace(',', '.')
df['EVs per Level 2 Port'] = df['EVs per Level 2 Port'].astype(float)

In [89]:
#Eliminamos filas 63 y 64 correspondientes a ubicaciones desconocidas.
#Los datos se visualizarÃ¡n en un mapa por lo que estas filas no serÃ¡n utilizadas.
df.drop([63,64], axis=0, inplace=True) 
df

,REDC,County,Light-Duty Vehicles,BEVs on the Road,PHEVs on the Road,EVs on the Road,Level 2 Ports,DCFC Ports,LDVs per 1k People,BEVs per 1k People,PHEVs per 1k People,BEVS per DCFC Ports,EVs per Level 2 Port,LD EV Market Share (%)
0,New York City,Manhattan,136854.0,4747.0,2190.0,6937.0,1047.0,27.0,84.40,2.93,1.35,175.814815,6.63,2.59
1,Mid-Hudson,Westchester County,389909.0,10098.0,4361.0,14459.0,368.0,109.0,402.91,10.43,4.51,92.642202,39.29,1.85
2,Southern Tier,Tompkins County,36530.0,733.0,950.0,1683.0,73.0,11.0,354.59,7.12,9.22,66.636364,23.05,1.67
3,Long Island,Nassau County,594841.0,13228.0,5337.0,18565.0,158.0,104.0,434.31,9.66,3.90,127.192308,117.50,1.65
4,Out of State,Out of State,80286.0,3640.0,757.0,4397.0,0.0,0.0,NaN,0.00,0.00,0.000000,NaN,1.64
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,Southern Tier,Chenango County,24338.0,54.0,103.0,157.0,6.0,0.0,498.17,1.11,2.11,0.000000,26.17,0.18
59,Western New York,Cattaraugus County,36160.0,55.0,97.0,152.0,18.0,12.0,494.67,0.75,1.33,4.583333,8.44,0.15
60,North Country,Lewis County,15936.0,18.0,34.0,52.0,6.0,0.0,631.10,0.71,1.35,0.000000,8.67,0.14
61,Western New York,Allegany County,20880.0,37.0,72.0,109.0,7.0,1.0,454.62,0.81,1.57,37.000000,15.57,0.13
62,Finger Lakes,Wyoming County,21215.0,40.0,60.0,100.0,8.0,0.0,525.29,0.99,1.49,0.000000,12.50,0.08

In [90]:
df.to_csv('ev_per_county_ny.csv', index=False)